// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDWdwtnJS8OouX5O4Dcfe-vonuTYbh5FY',
    appId: '1:135387304930:web:56b4744f1be3438e4e9fbb',
    messagingSenderId: '135387304930',
    projectId: 'stuteach-7ce8c',
    authDomain: 'stuteach-7ce8c.firebaseapp.com',
    storageBucket: 'stuteach-7ce8c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsqrA9wCRtadHoog99rMq0SdyrQ4WDvCc',
    appId: '1:135387304930:android:1d06351630c6d1d04e9fbb',
    messagingSenderId: '135387304930',
    projectId: 'stuteach-7ce8c',
    storageBucket: 'stuteach-7ce8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-FjfantVPQHHo8c8bepAUYObxrcrSn74',
    appId: '1:135387304930:ios:894a3398a12e524f4e9fbb',
    messagingSenderId: '135387304930',
    projectId: 'stuteach-7ce8c',
    storageBucket: 'stuteach-7ce8c.appspot.com',
    iosBundleId: 'com.example.stuTeach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-FjfantVPQHHo8c8bepAUYObxrcrSn74',
    appId: '1:135387304930:ios:894a3398a12e524f4e9fbb',
    messagingSenderId: '135387304930',
    projectId: 'stuteach-7ce8c',
    storageBucket: 'stuteach-7ce8c.appspot.com',
    iosBundleId: 'com.example.stuTeach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDWdwtnJS8OouX5O4Dcfe-vonuTYbh5FY',
    appId: '1:135387304930:web:247354161ead23f34e9fbb',
    messagingSenderId: '135387304930',
    projectId: 'stuteach-7ce8c',
    authDomain: 'stuteach-7ce8c.firebaseapp.com',
    storageBucket: 'stuteach-7ce8c.appspot.com',
  );
}
